package org.opensrp.common.util;

public enum PermissionName {
	PERM_UPDATE_PASSWORD, PERM_WRITE_USER, PERM_READ_USER, PERM_UPDATE_USER, PERM_DELETE_USER, PERM_WRITE_ROLE, PERM_READ_ROLE, PERM_UPDATE_ROLE, PERM_DELETE_ROLE, PERM_READ_HOUSEHOLD_LIST, PERM_READ_ELCO_LIST, PERM_READ_CHILD_LIST, PERM_READ_MOTHER_LIST, PERM_READ_EXPORT, PERM_READ_HOUSEHOLD, PERM_READ_ELCO, PERM_READ_CHILD, PERM_READ_MOTHER, PERM_VISIT_HOME, PERM_EXPORT_DATA
	
}
