package org.opensrp.common.util;

public enum PermissionName {
	PERM_UPDATE_PASSWORD, PERM_WRITE_USER, PERM_READ_USER, PERM_UPDATE_USER,
	PERM_DELETE_USER, PERM_WRITE_ROLE, PERM_READ_ROLE, PERM_UPDATE_ROLE, 
	PERM_DELETE_ROLE, PERM_READ_HOUSEHOLD_LIST,
	PERM_READ_CHILD_LIST, PERM_READ_MOTHER_LIST,
	PERM_READ_HOUSEHOLD,  PERM_READ_CHILD, PERM_READ_MOTHER,
	PERM_VISIT_HOME, PERM_WRITE_LOCATION,PERM_READ_LOCATION,
	PERM_UPDATE_LOCATION,PERM_HIERARCHY_LOCATION,PERM_READ_TEAM,
	PERM_WRITE_TEAM,PERM_UPDATE_TEAM,PERM_READ_LOCATION_TAG,
	PERM_WRITE_LOCATION_TAG,PERM_UPDATE_LOCATION_TAG,PERM_READ_TEAM_MEMBER,
	PERM_WRITE_TEAM_MEMBER,PERM_UPDATE_TEAM_MEMBER,
}
